version: 2
jobs:
  service_up:
    filters:
      branches:
        only: master
    docker:
    - image: circleci/python:3.6.6-node
    working_directory: ~/singnet
    environment:
      ORG: singnet
      DOCKER_ORG: singularitynet
      DOCKER_CONTEXT: https://github.com/singnet/opencog-services.git
      DOCKER_IMAGE_NAME: senna_opencog_services
      DOCKER_BASIC_IMAGE_NAME: senna_opencog_services_basic
      DOCKER_CONTAINER_NAME: SENNA_OPENCOG_SERVICES
      REPO_NAME: opencog-services
      SERVICE_NAME: opencog
      SERVICE_RUN_SCRIPT: bin/server
      TEST_SCRIPT: bin/runTests
      COMPLIANCE_CHECK_SCRIPT: scripts/compliance_check.sh
      SNETD_PORT: 7031
    steps:
    - run:
        name: Build basic docker image
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            docker image build -t $DOCKER_BASIC_IMAGE_NAME https://raw.githubusercontent.com/singnet/opencog-services/master/.circleci/basic_dockerfile
          EOF
    - run:
        name: Build Docker container
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            docker stop $DOCKER_CONTAINER_NAME || true
            docker rm $DOCKER_CONTAINER_NAME || true 
            docker build --no-cache -t $DOCKER_IMAGE_NAME $DOCKER_CONTEXT
          EOF
    - run:
        name: Start Service
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            docker run --name $DOCKER_CONTAINER_NAME \
              --restart unless-stopped \
              -p $SNETD_PORT:$SNETD_PORT \
              -di $DOCKER_IMAGE_NAME $SERVICE_RUN_SCRIPT
          EOF
    - run:
        name: Execute compliance check
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            docker exec -i $DOCKER_CONTAINER_NAME $COMPLIANCE_CHECK_SCRIPT
          EOF
    - run:
        name: Execute regression tests
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            docker exec -i $DOCKER_CONTAINER_NAME $TEST_SCRIPT
          EOF

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - service_up
